### ISSUE TITLE
Aggiunta Pre-Output

### ISSUE THREAD

**Issue by MarcoGalliMove** [AndSalaMove/movespad#2]
- Aggiungere ai pre-output la potenza di picco del Laser

**Comment by AndSalaMove** [comment]
@MarcoGalliMove intendi la potenza di picco di tutto il laser? Perché la power per pixel è già un valore "di picco"

**Comment by MarcoGalliMove** [comment]
Si intendevo la potenza di picco di tutto il laser. Forse a questo punto uniformerei entrambe le potenze, le metterei entrambe come potenza media, lo scriverei nelle descrizioni e nei pre-output fornirei le potenze di picco
